### ISSUE TITLE
Pre-processed data not accessible

### ISSUE THREAD

**Issue by giuseppeCoccia** [gchrupala/peppa#52]
Hi, 
I tried to access the pre-processed video snippets from `https://surfdrive.surf.nl/files/index.php/s/S9HA9wicV7kCwet` as you explained in the main README but I got the message "This share is password-protected". I couldn't find the password in your instructions, so could you please help me accessing your data?
Thanks in advance for your help.

**Comment by gchrupala** [comment]
Please send me an email.
